### PR TITLE
Get the URI without GET parameters

### PR DESCRIPTION
**Pull request by klj613**
By using `getPathInfo()` it will get the URI without the GET parameters (e.g. ?foo=bar) which breaks the breadcrumb functionality as it won't find any matching routes.

### CODE REVIEW

**Comment by Jack12816** [comment]
Please merge this. Using getPathInfo() will only return the route part without the environment.

getRequestUri() -> /app_dev.php/author/sidebar/1/edit [Unable to match -> ResourceNotFoundException]

getPathInfo() -> /author/sidebar/1/edit [Match perfectly fine, all is working]

**Comment by Jack12816** [comment]
Even better would be exception handling for router match method.
Say you are in a action that only allows POST requests, and you want
to forward to another action on a error which allows GET requests a
MethodNotAllowedException will be thrown. Here is a quick fix for this case.

``` diff
--- vendor/xi/breadcrumbs-bundle/Xi/Bundle/BreadcrumbsBundle/Twig/Extension/BreadcrumbExtension.php.old 2012-10-10 15:10:09.000000000 +0200
+++ vendor/xi/breadcrumbs-bundle/Xi/Bundle/BreadcrumbsBundle/Twig/Extension/BreadcrumbExtension.php 2012-10-08 18:24:08.000000000 +0200
@@ -4,6 +4,7 @@

 use Twig_Extension;
 use Twig_Function_Method;
+use \Symfony\Component\Routing\Exception\MethodNotAllowedException;

 /**
  * Extends Twig to output breadcrumbs
@@ -53,11 +54,17 @@
         $request = $this->container->get('request');

         $route = $request->get('_route');
-        $params = $router->match($request->getRequestUri());
+
+        try {
+            $params = $router->match($request->getPathInfo());
+        }
+        catch (MethodNotAllowedException $e) {
+            return;
+        }

         return $this->container->get("templating")->render(
             "XiBreadcrumbsBundle:Default:breadcrumbs.html.twig",
-            array( 'breadcrumbs' => $this->service->getBreadcrumbs($route, $params))
+            array( 'breadcrumbs' => $this->service->getBreadcrumbs((string)$route, $params))
         );
     }
```

**Update:**
Casting $route to string prevents nasty exceptions if a controller action does not have a route.
$route will in this case be NULL and so it will be a empty string which can be processed.

**Comment by peterhil** [comment]
Hi! This is a good improvement. I'll check this out.

**Comment by peterhil** [comment]
Merged. I had merged Symfony 2.1 changes into master, so I made my local branches and merged them.

See https://github.com/xi-project/xi-bundle-breadcrumbs/pull/8 for Symfony 2.0 and
https://github.com/xi-project/xi-bundle-breadcrumbs/pull/9 for Symfony 2.1.

**Comment by Jack12816** [comment]
+1 :)

**Pull request closed without merging**
